project_name: botctl

checksum:
  name_template: "checksums.txt"

builds:
  - main: .
    binary: botctl
    ldflags:
      - -s -w -X main.version={{ .Version }}
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    name_template: "botctl-{{ .Tag }}-{{ .Os }}-{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  use: github
  format: "[`{{ .SHA }}`](https://github.com/montanaflynn/botctl/commit/{{ .SHA }}) {{ .Message }}"
  abbrev: 7
  groups:
    - title: Features
      regexp: "^.*feat.*:+.*$"
      order: 0
    - title: Bug Fixes
      regexp: "^.*fix.*:+.*$"
      order: 1
    - title: Performance
      regexp: "^.*perf.*:+.*$"
      order: 2
    - title: Refactoring
      regexp: "^.*refactor.*:+.*$"
      order: 3
    - title: Documentation
      regexp: "^.*docs.*:+.*$"
      order: 4
    - title: Testing
      regexp: "^.*test.*:+.*$"
      order: 5
    - title: CI
      regexp: "^.*ci.*:+.*$"
      order: 6
    - title: Chores
      regexp: "^.*chore.*:+.*$"
      order: 7
    - title: Others
      order: 999

release:
  github:
    owner: montanaflynn
    name: botctl
